---
# tasks file for devtools

- name: install system tools
  apt: pkg={{ item }} state=present
  with_items:
    - htop
    - zsh

- name: Install testinfra
  pip: name=testinfra

# zsh conf

- name: zsh default shell
  user: name=vagrant shell=/usr/bin/zsh

- name: Get oh-my-zsh from git
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh accept_hostkey=True update=no

- name: Give oh-my-zsh permissions for vagrant
  file: dest=/home/vagrant/.oh-my-zsh owner=vagrant group=vagrant recurse=yes

- name: Zsh conf
  template: src=zshrc.j2 dest=/home/vagrant/.zshrc owner=vagrant group=vagrant

# node

- name: check node installed
  stat: path=/opt/node-{{ node_version }}-linux-x64/bin/npm
  register: npm_installed

- name : download node
  get_url: url=https://nodejs.org/dist/{{ node_version }}/node-{{ node_version }}-linux-x64.tar.xz dest=/tmp/node-{{ node_version }}-linux-x64.tar.xz validate_certs=no
  when: not npm_installed.stat.exists

- name: unarchive node
  unarchive: src=/tmp/node-{{ node_version }}-linux-x64.tar.xz dest=/tmp copy=no
  when: not npm_installed.stat.exists

- name: move node directory to /opt
  command: mv /tmp/node-{{ node_version }}-linux-x64 /opt/
  when: not npm_installed.stat.exists

- name: symlink node and npm
  file:
    src: /opt/node-{{ node_version }}-linux-x64/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    state: link
  with_items:
    - node
    - npm
