---
# tasks file for devtools

- name: install system tools
  apt: pkg={{ item }} state=present
  with_items:
    - htop

- name: Install testinfra
  pip: name=testinfra

# node

- name: check node installed
  stat: path=/opt/node-{{ node_version }}-linux-x64/bin/npm
  register: npm_installed

- name : download node
  get_url: url=https://nodejs.org/dist/{{ node_version }}/node-{{ node_version }}-linux-x64.tar.xz dest=/tmp/node-{{ node_version }}-linux-x64.tar.xz validate_certs=no
  when: not npm_installed.stat.exists

- name: unarchive node
  unarchive: src=/tmp/node-{{ node_version }}-linux-x64.tar.xz dest=/tmp copy=no
  when: not npm_installed.stat.exists

- name: move node directory to /opt
  command: mv /tmp/node-{{ node_version }}-linux-x64 /opt/
  when: not npm_installed.stat.exists

- name: symlink node and npm
  file:
    src: /opt/node-{{ node_version }}-linux-x64/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    state: link
  with_items:
    - node
    - npm
