---
# tasks file for devtools

- name: install gui
  apt: pkg={{ item }} state=installed
  with_items:
    - lxde

- name: create xorg custom conf
  file: dest=/etc/X11/xorg.conf.d state=directory

- name: xorg keyboard fr
  template: src=00-keyboard.conf.j2 dest=/etc/X11/xorg.conf.d/00-keyboard.conf

- name: add git ppa
  apt_repository: repo='ppa:git-core/ppa'

- name: install common editors via apt (vim/nano/gedit/emacs)
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - nano
    - gedit
    - emacs

- name: install common useful devtools(git/tig/htop/meld/curl/wget/gdebi)
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - vim
    - tig
    - htop
    - meld
    - curl
    - wget
    - gdebi
    - zsh
    - terminator
    - firefox
    - firefox-locale-fr
    - firefox-locale-en
    - libssl-dev
    - openssl
    - python-dev

- name: add atom and sublime ppa's
  apt_repository: repo='ppa:{{ item }}'
  with_items:
    - webupd8team/atom
    - webupd8team/sublime-text-3

- name: install atom and sublime
  apt: pkg={{ item }} state=installed
  with_items:
    - atom
    - sublime-text-installer

- name: install git
  apt: pkg=git state=installed

- name: Install virtualenvwrapper
  pip: name=virtualenvwrapper

- name: zsh default shell
  user: name=vagrant shell=/usr/bin/zsh

- name: Get oh-my-zsh from git
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh accept_hostkey=True update=no

- name: Give oh-my-zsh permissions for vagrant
  file: dest=/home/vagrant/.oh-my-zsh owner=vagrant group=vagrant recurse=yes

- name: Zsh conf
  template: src=zshrc.j2 dest=/home/vagrant/.zshrc owner=vagrant group=vagrant

- name: create .vim directory
  file: dest=/home/vagrant/.vim owner=vagrant group=vagrant state=directory

- name: deploy vimrc
  template: src=vimrc.j2 dest=/home/vagrant/.vim/vimrc owner=vagrant group=vagrant

- name: symlink vimrc
  file: src=/home/vagrant/.vim/vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant state=link

- name: Get vim solidity
  git: repo=https://github.com/tomlion/vim-solidity.git dest=/tmp/vim-solidity accept_hostkey=True update=no

- name: deploy solidity for vim
  copy: src=/tmp/vim-solidity/{{ item }} dest=/home/vagrant/.vim owner=vagrant group=vagrant
  with_items:
    - indent
    - ftdetect
    - syntax

- name: swap script
  git: repo=https://gist.github.com/9dd8d2d1a556b8bf9c82.git dest=/home/vagrant/swap accept_hostkey=True update=no

- name: Give permissions to vagrant swap
  file: dest=/home/vagrant/swap owner=vagrant group=vagrant recurse=yes

- name: Give permissions to vagrant swap
  file: dest=/home/vagrant/swap/increase_swap.sh owner=vagrant group=vagrant mode=0550

# install python3.5

- name: add ppa for python35
  apt_repository: repo='ppa:fkrull/deadsnakes' update_cache=yes

- name: install python35
  apt: pkg=python3.5 state=installed

- name : download python3.5
  get_url: url=https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tgz dest=/tmp/Python-3.5.0.tgz validate_certs=no

- name: unarchive python35
  unarchive: src=/tmp/Python-3.5.0.tgz dest=/tmp copy=no

# Slack

- name : download slack
  get_url: url=https://downloads.slack-edge.com/linux_releases/slack-desktop-2.1.2-i386.deb dest=/tmp/slack-desktop-2.1.2-i386.deb validate_certs=no

- name: check slack installed
  stat: path=/usr/bin/slack
  register: slack_installed

- name: install slack
  command: gdebi -n /tmp/slack-desktop-2.1.2-i386.deb
  become: yes
  when: not slack_installed.stat.exists

# NPM

- name: check slack installed
  stat: path=/opt/{{ node_version }}/bin/npm
  register: npm_installed

- name : download node
  get_url: url=https://nodejs.org/dist/v6.9.1/{{ node_version }}.tar.xz dest=/tmp/node-v6.9.1-linux-x86.tar.xz validate_certs=no
  when: not npm_installed.stat.exists

- name: unarchive node
  unarchive: src=/tmp/{{ node_version }}.tar.xz dest=/tmp copy=no
  when: not npm_installed.stat.exists

- name: move node directory to /opt
  command: mv /tmp/{{ node_version }} /opt
  when: not npm_installed.stat.exists

- name: symlink node and npm
  file:
    src: /opt/{{ node_version }}/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    state: link
  with_items:
    - node
    - npm
